const seedRequests=[
 {time:'10:42:18',date:'今天 10:42',model:'deepseek-chat',project:'DSH Web',input:2840,output:981,cost:.0214,status:'success'},
 {time:'10:38:04',date:'今天 10:38',model:'gpt-4o',project:'TokenMonitor',input:5120,output:1420,cost:.0682,status:'success'},
 {time:'09:51:33',date:'今天 09:51',model:'deepseek-reasoner',project:'DSH API',input:8900,output:3210,cost:.0876,status:'success'},
 {time:'昨天 22:17',date:'昨天 22:17',model:'claude-3.7-sonnet',project:'Research',input:4350,output:1890,cost:.0529,status:'success'},
 {time:'昨天 21:46',date:'昨天 21:46',model:'gemini-2.5-pro',project:'Prototype',input:2200,output:0,cost:0,status:'error'},
 {time:'昨天 18:20',date:'昨天 18:20',model:'deepseek-chat',project:'DSH Web',input:3300,output:1120,cost:.0258,status:'success'},
 {time:'周一 16:05',date:'周一 16:05',model:'gpt-4o',project:'TokenMonitor',input:6800,output:2300,cost:.0912,status:'success'},
 {time:'周一 13:20',date:'周一 13:20',model:'deepseek-chat',project:'DSH CLI',input:1800,output:670,cost:.0148,status:'success'}
];
const state={requests:JSON.parse(localStorage.getItem('tm-requests')||'null')||seedRequests,budget:Number(localStorage.getItem('tm-budget')||100),alert:Number(localStorage.getItem('tm-alert')||80),period:7};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>'$'+Number(n).toFixed(n<1?3:2), num=n=>Number(n).toLocaleString('en-US'), totalTokens=r=>r.input+r.output;
function save(){localStorage.setItem('tm-requests',JSON.stringify(state.requests));localStorage.setItem('tm-budget',state.budget);localStorage.setItem('tm-alert',state.alert)}
function aggregate(){const rs=state.requests, tokens=rs.reduce((s,r)=>s+totalTokens(r),0), cost=rs.reduce((s,r)=>s+r.cost,0), successful=rs.filter(r=>r.status==='success').length;return {rs,tokens,cost,successful,input:rs.reduce((s,r)=>s+r.input,0),output:rs.reduce((s,r)=>s+r.output,0)}}
function renderMetrics(){const a=aggregate();const cards=[['总 Token',''+num(a.tokens),'较上周期 +18.4%', 'var(--mint)','↗ 18.4%'],['总费用',money(a.cost),'较上周期 +12.8%','var(--purple)','↗ 12.8%'],['请求次数',num(a.rs.length),'成功率 '+Math.round(a.successful/Math.max(1,a.rs.length)*100)+'%','var(--orange)','↗ 7.2%'],['平均请求',money(a.cost/Math.max(1,a.rs.length)),'每次请求平均费用','var(--mint)','稳定']];$('#metricGrid').innerHTML=cards.map(c=>'<div class="metric-card" style="--accent:'+c[3]+'"><div class="metric-label">'+c[0]+'<b>'+c[4]+'</b></div><strong class="metric-value">'+c[1]+'</strong><small class="metric-sub">'+c[2]+'</small></div>').join('')}
function renderChart(){const c=$('#usageChart'),ctx=c.getContext('2d'),rect=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=rect.width*d;c.height=rect.height*d;ctx.scale(d,d);const w=rect.width,h=rect.height,p={l:4,r:8,t:15,b:25}, values=[.29,.42,.35,.57,.46,.73,.64],out=[.15,.25,.22,.31,.28,.44,.39],max=.85;ctx.clearRect(0,0,w,h);ctx.font='10px DM Mono';ctx.fillStyle='#7189a1';['0','20k','40k','60k','80k'].forEach((v,i)=>{const y=p.t+(h-p.t-p.b)*i/4;ctx.fillText(v,0,y+3);ctx.strokeStyle='rgba(33,54,78,.75)';ctx.beginPath();ctx.moveTo(35,y);ctx.lineTo(w,y);ctx.stroke()});function line(arr,color){ctx.beginPath();arr.forEach((v,i)=>{const x=40+(w-50)*i/(arr.length-1),y=p.t+(h-p.t-p.b)*(1-v/max);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();arr.forEach((v,i)=>{const x=40+(w-50)*i/(arr.length-1),y=p.t+(h-p.t-p.b)*(1-v/max);ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()})}line(values,'#65f0c2');line(out,'#8275ff');['周一','周二','周三','周四','周五','周六','今天'].forEach((v,i)=>{ctx.fillStyle='#7189a1';ctx.fillText(v,40+(w-50)*i/6,h-5)})}
function renderBudget(){const a=aggregate(),percent=Math.min(100,a.cost/state.budget*100),ring=$('#budgetRing');ring.style.background='conic-gradient(var(--mint) '+percent*3.6+'deg,#1c3147 0deg)';$('#budgetPercent').textContent=Math.round(percent)+'%';$('#budgetUsed').textContent=money(a.cost);$('#budgetLimit').textContent=money(state.budget);$('#budgetForecast').textContent=money(a.cost*30/Math.max(1,state.period));$('#budgetInput').value=state.budget;$('#alertInput').value=state.alert;$('#projection').innerHTML=[['当前日均费用',money(a.cost/Math.max(1,state.period))],['预计月末费用',money(a.cost*30/Math.max(1,state.period))],['预警阈值',money(state.budget*state.alert/100)],['剩余可用',money(Math.max(0,state.budget-a.cost))]].map(x=>'<div class="projection-row"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')}
function status(r){return '<span class="status '+r.status+'">'+(r.status==='success'?'成功':'失败')+'</span>'}
function renderRecent(){const rs=aggregate().rs.slice(0,5);$('#recentTable').innerHTML=rs.map(r=>'<tr><td class="model-name">'+r.model+'</td><td>'+status(r)+'</td><td>'+num(totalTokens(r))+'</td><td>'+money(r.cost)+'</td><td>'+r.time+'</td></tr>').join('')}
function renderRequests(){const q=($('#requestSearch')?.value||$('#globalSearch')?.value||'').toLowerCase(),filter=$('#statusFilter')?.value||'all';const rs=state.requests.filter(r=>(filter==='all'||r.status===filter)&&[r.model,r.project,r.status].join(' ').toLowerCase().includes(q));$('#requestTable').innerHTML=rs.map(r=>'<tr><td>'+r.date+'</td><td class="model-name">'+r.model+'</td><td>'+r.project+'</td><td>'+num(r.input)+'</td><td>'+num(r.output)+'</td><td>'+num(totalTokens(r))+'</td><td>'+money(r.cost)+'</td><td>'+status(r)+'</td></tr>').join('')||'<tr><td colspan="8">没有匹配记录</td></tr>'}
function renderModels(){const map={};state.requests.forEach(r=>{map[r.model]??={tokens:0,cost:0,count:0,input:0,output:0};const m=map[r.model];m.tokens+=totalTokens(r);m.cost+=r.cost;m.count++;m.input+=r.input;m.output+=r.output});const all=Object.entries(map).sort((a,b)=>b[1].tokens-a[1].tokens),max=all[0]?.[1].tokens||1;$('#modelDistribution').innerHTML=all.map(([name,m],i)=>'<div class="model-row" style="--bar:'+(i%2?'var(--purple)':'var(--mint)')+'"><span>'+name+'</span><div class="bar"><i style="width:'+(m.tokens/max*100)+'%"></i></div><b>'+Math.round(m.tokens/aggregate().tokens*100)+'%</b></div>').join('');$('#modelCards').innerHTML=all.map(([name,m],i)=>'<article class="panel model-card"><div class="model-summary"><div><p class="eyebrow">MODEL '+String(i+1).padStart(2,'0')+'</p><h3>'+name+'</h3></div><strong class="big">'+num(m.tokens)+'</strong></div><dl><div><dt>请求数</dt><dd>'+m.count+'</dd></div><div><dt>费用</dt><dd>'+money(m.cost)+'</dd></div><div><dt>输入 Token</dt><dd>'+num(m.input)+'</dd></div><div><dt>输出 Token</dt><dd>'+num(m.output)+'</dd></div></dl></article>').join('')}
function render(){renderMetrics();renderChart();renderBudget();renderRecent();renderRequests();renderModels();$('#collectorTime').textContent='刚刚同步'}
function showView(view){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active',v.id===view+'View'));$('#pageHeading').textContent={overview:'用量总览',requests:'请求记录',models:'模型分析',budgets:'预算中心'}[view];$('#sidebar').classList.remove('open')}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-view-link]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewLink)));$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#periodSwitch').addEventListener('click',e=>{if(e.target.tagName==='BUTTON'){$$('#periodSwitch button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');state.period=+e.target.dataset.period;render()}});$('#globalSearch').addEventListener('input',renderRequests);$('#requestSearch').addEventListener('input',renderRequests);$('#statusFilter').addEventListener('change',renderRequests);window.addEventListener('resize',renderChart);
const modal=$('#usageModal');$('#addUsageButton').addEventListener('click',()=>modal.hidden=false);$$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>modal.hidden=true));$('#usageForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),r={model:f.get('model'),project:f.get('project'),input:+f.get('input'),output:+f.get('output'),cost:+f.get('cost'),status:f.get('status'),time:'刚刚',date:'刚刚'};state.requests.unshift(r);save();modal.hidden=true;e.target.reset();render();$('#toast').textContent='用量记录已添加';$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)});$('#budgetForm').addEventListener('submit',e=>{e.preventDefault();state.budget=+$('#budgetInput').value;state.alert=+$('#alertInput').value;save();renderBudget();$('#toast').textContent='预算设置已保存';$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)});$('#exportButton').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state.requests,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tokenmonitor-requests.json';a.click();URL.revokeObjectURL(a.href)});$('#themeButton').addEventListener('click',()=>document.body.classList.toggle('light'));render();